# -*- coding: utf-8 -*-
"""rascunho Simulator LoraWAN Network For Optimization in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLrY6jlhakS6pKZcEQTtvZ2Xfk2_yYL-

##Universidade Federal do Pará

Instituto de Tecnologia - UFPA

Ivan Igor Antunes Neves

Jasmine Priscila Leite de Araujo

Esse trabalho visa a promover o entendimento dinamico de redes Lpwans que utilizão o protocolo LoRaWAN e modulos LoRa


Grande parte dos simuladores desse tipo de rede é otimizado para analises específicas de comportamentos e aplicações únicas como: movimentação de end devices, retransmição, carga de gateway, modelos de propagação, algoritmos de otimização, eficiencia energética, colisões de pacotes, categorias de dispositivos, quantidades de canais de transmissões, variação de cofigurações de cada dispositivo, tipos de dados, largura de banda, quantidade de dispositivos na rede, posição, entre outros.


A proposta desse trabalho é integrar todas essas analises em um único simulador para mostrar comportamentos da rede apartir dos parametros configuraveis da rede

O simulador é composto por múltiplas classes que interagem para modelar o comportamento de uma rede LoRaWAN com dispositivos móveis, gateways, MAC layer (LoRaWAN MAC), consumo de energia e métricas de desempenho.


##Modelos

 1 - otmização é o Adaptive data rate (ADR)[2]

 2 - Vazão

 3 - Enegia

 4 - colisões

 5 - Transmissão e Retransmissão

 6 - interferencia

 7 - dispositivos [1]

https://docs.google.com/document/d/1I7gIEQOQKCz9xf3DIVwrf3-9Kl224FgL4KIPvxAX-Lg/edit?usp=sharing

[1] https://www.mouser.com/pdfdocs/semtech-lora-modem-design.pdf

[2]https://resources.lora-alliance.org/technical-specifications/adr-harmonize-state-transition-errata-on-the-lorawan-l2-1-0-3-specification

[3]https://www.sciencedirect.com/science/article/abs/pii/S1389128620311609

[4] "Long-range wireless technologies for IoT applications: A review"
Foco: Comparação entre tecnologias sem fio de longo alcance para IoT, incluindo LoRaWAN.

[5] "Investigation of Indoor LoRaWAN Signal Propagation for Real-World Applications"
📄 Foco: Análise da propagação do sinal LoRaWAN em ambientes internos.

[6] "Experimental Evaluation of LoRaWAN in NS-3"
📄 Foco: Avaliação da implementação do LoRaWAN no simulador NS-3.

[7] "The Effect of Temperature and Humidity on Indoor LoRa Propagation Model"
📄 Foco: Estudo do impacto da temperatura e umidade na propagação do sinal LoRa.

[8] "LoRaWAN Energy Consumption Analysis"
📄 Foco: Análise do consumo energético em dispositivos LoRaWAN.

[9]"Adaptive Algorithm for Spreading Factor Allocation in LoRaWAN"
📄 Foco: Algoritmo de alocação dinâmica do Spreading Factor para otimizar redes LoRaWAN.

[10] "LoRaWAN Network Energy Consumption and Throughput Analysis"
📄 Foco: Análise de consumo de energia e vazão (throughput) em redes LoRaWAN.

[11] "CupCarbon: A Smart City IoT Network Simulator"
📄 Foco: Simulador para IoT em ambientes urbanos, incluindo LoRaWAN.

[12] "PhySimulator: A High-Accuracy Physical Layer Simulator for LoRaWAN"
📄 Foco: Simulador físico avançado para modelar a camada PHY do LoRaWAN.

[13] https://www.alldatasheet.com/html-pdf/800241/SEMTECH/SX1278/6273/21/SX1278.html

## PARAMETROS
"""

# Configurações da simulação
num_devices = 50 # Numero de transmissores Lora
num_gateways = 1 # Numero de gateways
area_size = 100 # Area Km²
lambda_rate = 0.1 # fator de probabilidade de direção de movimento
speed = 6 # Velocidade de movimento dos devices caso a mobilidade seja True
sf_range = [7, 8, 9, 10, 11, 12] # Spread Factor [7, 8, 9, 10, 11, 12]
tx_power = 16 # Potencia de transmissão inicial em db
rx_power = 14 # Potencia de recepção inicial em db
idle_power = 2 # Potencia ociosa db
standby_power = 1.4 # Corrente consumida pelo dispositivo no estado de espera (mA)
voltage = 3.3 # tenção
receive_delay1 = 1 #Tempo de espera antes das janelas de recepção 1
receive_delay2 = 2 #Tempo de espera antes das janelas de recepção 2
rd1 = 1 #Período de dormência antes da recepção (segundos)
rd2 = 1 #Período de dormência depois da recepção (segundos)
trx1 = 1 #Tempo de recepção de pacotes na primeira janela (segundos)
trx2 = 2 #Tempo de recepção de pacotes na segunda janela (segundos)
frequency_mhz = [915000000] # Frequencia 433000000, 868000000, 915000000
ht_m = 5 # Altura do device em metros
hr_m = 30 # Altura do gateway em metros
bw = [125000] # Lagura de banda 125000, 250000, 500000
cr = 4/5 # code
pl = 80 # payload
simulation_time = 100 # Tempo de duração em segundos
adr_enabled = True #  adaptive data rate
mobility_enabled = True # mobilidade
model= "random_walk" # "gauss_markov" "levy_walk" "random_walk" "matrix" modelos de movimentação
model_pathloss = "cost_hata" #  "okumura_hata" "log_distance" "fspl" "cost_hata" "fading" modelos de propagação
k = 1.38e-23  # Constante de Boltzmann (J/K) para calcular o ruido de fundo
temperatura = 294.15  # Temperatura de referência (K) para calcular o ruido de fundo em kelvin
noise_figure = - 30 # Fator de ruído (em dB), pode ser ajustado

"""## Bibliotecas Python"""

import csv
import uuid  # Para gerar um identificador único para cada pacote
import random
import numpy as np
import math
import matplotlib.pyplot as plt
from collections import Counter

"""##Packet


"""

class Packet:
    def __init__(self, device_id, sf,tx_power, bw, freq, rssi, arrival_time, rectime, packet_type="uplink"):
        """
        Inicializa um pacote LoRaWAN.

        Parâmetros:
        - device_id: ID do dispositivo que transmite o pacote
        - sf: Spreading Factor do dispositivo
        - bw: Largura de banda usada na transmissão
        - freq: Frequência da transmissão
        - rssi: Intensidade do sinal recebido (RSSI)
        - arrival_time: Tempo de chegada do pacote
        - rectime: Tempo de recepção do pacote
        - packet_type: Tipo do pacote (uplink, downlink, critical)
        """
        self.packet_id = uuid.uuid4()  # 🔹 Identificador único para rastrear pacotes
        self.device_id = device_id
        self.sf = sf
        self.tx_ = tx_power
        self.bw = bw
        self.freq = freq
        self.rssi = rssi
        self.arrival_time = arrival_time
        self.rectime = rectime
        self.collided = False
        self.received = True
        self.packet_type = packet_type
        self.sir = None
        self.snr = None
        self.noise_floor = None
    def __repr__(self):
            """Representação amigável do pacote para debug e logs."""
            return (f"<Packet ID={self.packet_id} | Device={self.device_id} | SF={self.sf} | TP: {self.tx_power} RSSI={self.rssi:.2f} dBm | "
                    f"SNR={self.snr:.2f} dB | Noise Floor={self.noise_floor:.2f} dBm | Collided={self.collided} | Type={self.packet_type}>")

"""##PacketTracker"""

class PacketTracker:
    def __init__(self):
        self.packets = []  # 📦 Lista de pacotes originais transmitidos na rede
        self.retransmitted_packets = []  # ♻️ Pacotes retransmitidos
        self.packet_history = {}  # 📜 Histórico de pacotes por dispositivo
        self.total_retransmissions = 0  # 🔄 Contador global de retransmissões
        self.unique_packet_count = 0  # 🔢 Contador de pacotes únicos para rastreamento

    def add_packet(self, packet, is_retransmission=False):
        """
        Adiciona um pacote ao rastreador de pacotes e registra no histórico do dispositivo.
        - Se for retransmissão (`is_retransmission=True`), adiciona à lista de retransmissões.
        """
        if is_retransmission:
            self.retransmitted_packets.append(packet)
            self.total_retransmissions += 1
            print(f"♻️ [LOG] Retransmissão registrada: Dispositivo {packet.device_id} | Total retransmissões: {self.total_retransmissions}")
        else:
            self.packets.append(packet)
            self.unique_packet_count += 1
            print(f"📦 [LOG] Pacote original armazenado: Dispositivo {packet.device_id} | Total pacotes únicos: {self.unique_packet_count}")


        if packet.device_id not in self.packet_history:
            self.packet_history[packet.device_id] = []
        self.packet_history[packet.device_id].append(packet)

    def get_stats(self):
        """Retorna estatísticas gerais sobre a transmissão de pacotes na rede."""
        total_packets = len(self.packets) + len(self.retransmitted_packets)

        if total_packets == 0:
            return {
                "Total Pacotes": 0,
                "Colisões": 0,
                "Retransmissões": 0,
                "Entregues com Sucesso": 0,
                "Taxa de Entrega (PDR)": 0.00
            }


        collided_packets = sum(1 for p in self.packets + self.retransmitted_packets if getattr(p, "collided", False))
        successful_packets = total_packets - collided_packets

        pdr = round((successful_packets / total_packets) * 100, 2) if total_packets > 0 else 0.00


        return {
            "Total Pacotes": total_packets,
            "Colisões": collided_packets,
            "Retransmissões": self.total_retransmissions,
            "Entregues com Sucesso": successful_packets,
            "Taxa de Entrega (PDR)": pdr
        }

    def get_device_stats(self, device_id):
        """
        Retorna estatísticas de pacotes específicos para um dispositivo.
        """
        packets = self.packet_history.get(device_id, [])
        total_packets = len(packets)

        if total_packets == 0:
            return {
                "Device ID": device_id,
                "Total Pacotes": 0,
                "Colisões": 0,
                "Retransmissões": 0,
                "Entregues com Sucesso": 0,
                "Taxa de Entrega (PDR)": "0.00%"
            }

        collided_packets = sum(1 for p in packets if getattr(p, "collided", False))
        retransmissions = sum(1 for p in packets if p in self.retransmitted_packets)
        successful_packets = total_packets - collided_packets

        pdr = round((successful_packets / total_packets) * 100, 2)

        return {
            "Device ID": device_id,
            "Total Pacotes": total_packets,
            "Colisões": collided_packets,
            "Retransmissões": retransmissions,
            "Entregues com Sucesso": successful_packets,
            "Taxa de Entrega (PDR)": f"{pdr:.2f}%"
        }

    def export_device_log(self, filename="device_log.csv"):
        """
        Exporta um log detalhado de cada dispositivo ao longo do tempo.
        Inclui SF, RSSI, Tipo de Tráfego, Posições e Distância ao Gateway.
        """
        try:
            if not self.devices:  # 🚨 Verifica se há dispositivos registrados
                print("⚠️ Nenhum dispositivo encontrado. O log não será gerado.")
                return

            with open(filename, mode="w", newline="") as file:
                writer = csv.writer(file)
                writer.writerow(["Tempo", "Device ID", "SF", "RSSI", "Tipo de Tráfego", "Posição (X, Y)", "Distância do Gateway", "Gateway Conectado"])

                total_entries = 0  # Contador para verificar quantas linhas foram registradas

                for device in self.devices:
                    if device.device_id not in self.positions["devices"]:  # 🚨 Verifica se há posições registradas
                        print(f"⚠️ Nenhuma posição encontrada para o dispositivo {device.device_id}. Ignorando...")
                        continue

                    for t, (x, y) in enumerate(self.positions["devices"][device.device_id]):
                        best_gateway, distance, best_rssi = self.find_closest_gateway(device)

                        best_rssi = best_rssi if best_rssi is not None else "N/A"
                        distance = f"{distance:.2f}" if distance is not None else "N/A"
                        best_gateway = best_gateway if best_gateway is not None else "N/A"

                        writer.writerow([
                            t,  # Tempo da simulação
                            device.device_id,
                            device.sf,
                            best_rssi,
                            device.traffic_type,
                            f"({x:.2f}, {y:.2f})",
                            distance,
                            best_gateway
                        ])

                        total_entries += 1  # Atualiza contador

                if total_entries > 0:
                    print(f"📄 Log dos dispositivos exportado para {filename} com {total_entries} registros.")
                else:
                    print("⚠️ Nenhum dado registrado no log. Verifique a simulação.")

        except Exception as e:
            print(f"❌📄 Erro ao exportar log dos dispositivos: {e}")


    def clear_packets(self):
        """
        Limpa o histórico de pacotes, incluindo retransmissões.
        """
        self.packets.clear()
        self.retransmitted_packets.clear()
        self.packet_history.clear()
        self.total_retransmissions = 0  #  Zera contador de retransmissões
        self.unique_packet_count = 0  #  Zera contador de pacotes únicos
        print("🧹 Histórico de pacotes e retransmissões limpo.")

"""## EnergyModel"""

import numpy as np

class EnergyModel:
    def __init__(self, tx_power, rx_power, idle_power, standby_power, n_devices, network_throughput, voltage=3.3):
        """
        Modelo de consumo de energia de um dispositivo LoRaWAN baseado na equação matemática fornecida.

        Parâmetros:
        - tx_power: Corrente ao transmitir (mA)
        - rx_power: Corrente ao receber (mA)
        - idle_power: Corrente em estado inativo (mA)
        - standby_power: Corrente no estado de espera (mA)
        - num_devices: Número total de dispositivos na rede
        - network_throughput: Objeto da classe NetworkThroughput para obter o ToA médio, p(s) e N_c
        - voltage: Tensão da bateria (V) (Padrão: 3.3V)
        """
        self.tx_power = tx_power  # Corrente de transmissão (mA)
        self.rx_power = rx_power  # Corrente de recepção (mA)
        self.idle_power = idle_power  # Corrente em estado inativo (mA)
        self.standby_power = standby_power  # Corrente no estado de espera (mA)
        self.num_devices =num_devices  # Número de dispositivos na rede
        self.voltage = voltage  # Tensão da bateria (V)
        self.energy_consumed = 0  # Energia total consumida (mWh)
        self.network_throughput = network_throughput  # Objeto que calcula o ToA, p(s) e N_c

    def update_energy(self, mode, duration, device, rd1, rd2, trx1, trx2, receive_delay1, receive_delay2):
        """
        Atualiza o consumo de energia do dispositivo usando o modelo matemático fornecido.

        Parâmetros:
        - mode: Modo de operação ('transmit', 'receive', 'idle')
        - duration: Tempo total do ciclo de transmissão (segundos)
        - device: O dispositivo que está consumindo energia
        - rd1, rd2: Tempo de dormência antes e depois da recepção (segundos)
        - trx1, trx2: Tempo de recepção 1 e 2 (segundos)
        - receive_delay1, receive_delay2: Delays da recepção (segundos)
        """
        if duration <= 0:
            print(f"🔋⚠️ [LOG] Duração inválida para atualização de energia: {duration}s. Ignorando...")
            return


        n_covered = self.network_throughput.calculate_covered_devices()


        if n_covered == 0:
            print(f"⚠️ [LOG ENERGY] Nenhum dispositivo coberto. Energia não será atualizada para Device {device.device_id}.")
            return


        toa_dict = self.network_throughput.calculate_avg_airtime()
        toa = toa_dict.get(device.sf, 0)
        #print(f"air time :{toa}")

        sf_proportions = self.network_throughput.calculate_sf_proportions()
        p_s = sf_proportions.get(device.sf, 0)
        #print(f"[LOG ENERGY]proporção;{p_s}")


        e_active = (1/2) * p_s * n_covered * self.voltage * (
            (toa * self.tx_power) + (rd1 * self.standby_power) + (trx1 * self.rx_power)
        ) + (1/2) * p_s * n_covered * self.voltage * (
            (toa * self.tx_power) + ((rd2 - trx1) * self.standby_power) + ((trx1 + trx2) * self.rx_power)
        )


        e_idle = (1/2) * p_s * n_covered * self.voltage * (
            (duration - (toa + trx1 + receive_delay1)) * self.idle_power
        ) + (1/2) * p_s * n_covered * self.voltage * (
            (duration - (toa + receive_delay2 + trx2)) * self.idle_power
        )


        energy_total = e_active + e_idle
        self.energy_consumed += energy_total


        print(f"🔋 [LOG ENEGY] ToA: {toa:.2f}s | p(s): {p_s:.4f} | N_c: {n_covered} | "
              f"Modo: {mode.upper()} | Tempo: {duration:.2f}s | Consumo: {self.energy_consumed:.2f} mWh")

    def log_energy(self):
        """Exibe o consumo total de energia do dispositivo."""
        print(f"🔋 [LOG ENERGY] Consumo total de energia: {self.energy_consumed:.2} mWh")

    def reset_energy(self):
        """Reseta o consumo de energia para zero."""
        self.energy_consumed = 0
        print("🔋 [LOG] Consumo de energia resetado.")

"""##EndDevice"""

class EndDevice:
    def __init__(self, device_id, x, y, lambda_rate, speed, sf_range, tx_power,  bw, cr, pl, frequency_mhz, network, mobility_enabled=True, model="random_walk"):
        """
        Inicializa um dispositivo LoRaWAN.

        Parâmetros:
        - device_id: ID único do dispositivo.
        - x, y: Posição inicial do dispositivo.
        - lambda_rate: Taxa de movimentação do dispositivo.
        - speed: Velocidade do dispositivo.
        - sf_range: Lista de SFs disponíveis.
        - tx_power: Potência de transmissão.
        - Sensibilidade: Sensibilidade do receptor.
        - bw: Banda disponível.
        - cr: Código de correção de erro.
        - pl: Tamanho da carga útil (payload).
        - frequency_mhz: Lista de frequências disponíveis.
        - network: Referência ao objeto `Network`.
        - mobility_enabled: Se a mobilidade está ativada.
        - model: O modelo de mobilidade do dispositivo (ex: "random_walk").
        """
        self.device_id = device_id
        self.x = x
        self.y = y
        self.lambda_rate = lambda_rate
        self.speed = speed
        self.sf = random.choice(sf_range)
        self.tx_power = tx_power

        self.cr = cr
        self.pl = pl
        self.bw = random.choice(bw)
        self.rssi = None
        self.freq = random.choice(frequency_mhz)
        self.snr = None
        self.coverage_status = True

        self.retransmission_attempts = 0
        self.max_retransmissions = 10
        self.lorawan_class = random.choice(['A', 'B', 'C'])
        self.traffic_type = random.choice(["periodic", "sporadic", "critical"])
        self.network = network  # Referência à rede
        self.last_transmissions = []
        self.current_gateway = None
        self.snr_history = []
        self.rssi_history = []
        self.adr_enabled = True
        self.airtime = self.calculate_airtime()
        self.mobility_enabled = mobility_enabled
        self.model = model
        self.payload_size = self.calculate_payload_size()

        # Energy model now initialized with necessary parameters
        self.energy_model = EnergyModel(
            tx_power=self.tx_power,
            rx_power=14,  # Defina corretamente a potência de recepção
            idle_power=2,  # Defina corretamente a potência em idle
            standby_power=1.5,  # Defina corretamente a potência em standby
            n_devices=network.num_devices,  # Número de dispositivos na rede
            network_throughput=network.network_throughput,  # Referência à vazão da rede
            voltage=3.3  # Tensão padrão
        )

    def set_sensibilidade(self, sf, bw):
        """
        Define a sensibilidade com base no Spreading Factor (SF) e Largura de Banda (BW).
        """
#==========================tabela de sensibilidade errada=================================
        sensitivity_table = {
            (7, 125000): -123,
            (8, 125000): -126,
            (9, 125000): -129,
            (10, 125000): -132,
            (11, 125000): -135,
            (12, 125000): -137,
            (7, 250000): -120,
            (8, 250000): -123,
            (9, 250000): -126,
            (10, 250000): -129,
            (11, 250000): -132,
            (12, 250000): -134,
            (7, 500000): -117,
            (8, 500000): -120,
            (9, 500000): -123,
            (10, 500000): -126,
            (11, 500000): -129,
            (12, 500000): -131,
        }

        # Se não encontrar o par (sf, bw), retorna um valor muito baixo para garantir que o gateway não seja considerado

        return sensitivity_table.get((sf, bw),-999)  # Retorna um valor muito baixo para garantir a comparação correta

    def log_device_data(self, time):
        """
        Registra os dados do dispositivo a cada segundo.
        """
        # Encontra o melhor gateway para o dispositivo a cada segundo
        best_gateway, distance, best_rssi = self.network.find_closest_gateway(self)

        # Captura os parâmetros necessários
        device_data = [
            time,  # Tempo de simulação
            self.device_id,
            self.sf,  # Spreading Factor
            self.rssi if self.rssi is not None else "N/A",
            self.traffic_type,
            (self.x, self.y),  # Posição (X, Y)
            distance,
            best_gateway if best_gateway is not None else "N/A",  # Gateway conectado
            self.freq,
            self.bw,
            self.snr if self.snr is not None else "N/A",
            self.tx_power,
            best_rssi if best_rssi is not None else "N/A"
        ]
        self.network.export_device_log(device_data)

    def transmit(self, time):
        """Simula a transmissão de um pacote LoRaWAN e verifica colisões antes da retransmissão."""


        if self.device_id not in self.network.lorawan_mac.device_sessions:
            self.network.lorawan_mac.join_request(self)
            return None


        best_gateway, _, best_rssi = self.network.find_best_gateway(self)
        if best_gateway is None:
            return None


        self.current_gateway = best_gateway
        self.rssi = best_rssi

        rectime = self.calculate_airtime()
        self.energy_model.update_energy(
        mode='transmit',
        duration=rectime,
        device=self,
        rd1=rd1,
        rd2=rd2,
        trx1=trx1,
        trx2=trx2,
        receive_delay1=receive_delay1,
        receive_delay2=receive_delay2
    )

        # 📦 Cria um novo pacote
        packet = Packet(self.device_id, self.sf,self.tx_power, self.bw, self.freq, self.rssi, time, rectime)
        self.last_transmissions.append(packet)


        best_gateway.process_uplink(packet)


        self.network.packet_tracker.add_packet(packet)

        if self.network.adr_enabled:
            self.network.lorawan_mac.process_mac_commands(self)  # ✅ Ajuste de SF e potência centralizado


        if packet.collided:
            self.retransmit(time)

        return packet



    def retransmit(self, time):
        """Gerencia retransmissões em caso de colisão."""
        if self.retransmission_attempts >= self.max_retransmissions:
            print(f"📡❌🔃 [LOG END DEVICE] Dispositivo {self.device_id}: Número máximo de retransmissões atingido.")
            return None

        if self.wait_for_ack(time):
            print(f"🔰✅ [LOG END DEVICE] Dispositivo {self.device_id}: Pacote confirmado. Nenhuma retransmissão necessária.")
            return None

        backoff_time = random.uniform(1, 5)
        self.retransmission_attempts += 1
        retransmission_time = time + backoff_time

        retransmitted_packet = self.transmit(retransmission_time)
        if retransmitted_packet:
            self.network.packet_tracker.add_packet(retransmitted_packet, is_retransmission=True)

    def wait_for_ack(self, time):
        """Aguarda janelas RX1 e RX2 antes de retransmitir."""
        for delay in [1, 2]:  # RX1 e RX2
            wait_time = time + delay
            if self.network.lorawan_mac.check_ack(self.device_id, wait_time):
                return True  # Recebeu ACK
        return False  # Nenhum ACK recebido

    def process_ack(self, packet):
        """Processa um ACK recebido do gateway para evitar retransmissões desnecessárias."""
        if packet.received:
            self.retransmission_attempts = 0  # Reseta contador de tentativas


    def calculate_airtime(self):
        """Calcula o tempo de transmissão do pacote."""
        Tsym = (2.0 ** self.sf) / self.bw
        Tpream = (8 + 4.25) * Tsym
        payloadSymbNB = 8 + max(math.ceil((8.0 * self.pl - 4.0 * self.sf + 28 + 16 - 20 * 0) / (4.0 * (self.sf - 2 * 1))) * (self.cr + 4), 0)
        Tpayload = payloadSymbNB * Tsym
        return Tpream + Tpayload

    def calculate_payload_size(self):
        """Calcula o tamanho total do payload do pacote."""
        return self.pl + 13 + 2 + 4

    def move(self, area_size, mobility_enabled, model):
        """
        Simula a movimentação do dispositivo na rede usando diferentes modelos de mobilidade.

        Parâmetros:
        - area_size: Dimensão da área da rede
        - mobility_enabled: Ativa ou desativa a movimentação do dispositivo
        - model: Modelo de mobilidade ("random_walk", "gauss_markov", "levy_walk")

        Retorna:
        - time_interval: Tempo até a próxima movimentação
        - new_position: Nova posição (x, y)
        """
        if not mobility_enabled:
            return 0, (self.x, self.y)  # Dispositivo permanece no mesmo local

        time_interval = np.random.exponential(1 / self.lambda_rate)

        if model == "random_walk":
            angle = random.uniform(0, 2 * np.pi)
            dx = self.speed * np.cos(angle)
            dy = self.speed * np.sin(angle)

        elif model == "gauss_markov":
            alpha = 0.85  # Fator de suavização
            angle = alpha * getattr(self, "last_angle", random.uniform(0, 2 * np.pi)) + (1 - alpha) * random.uniform(0, 2 * np.pi)
            dx = self.speed * np.cos(angle)
            dy = self.speed * np.sin(angle)
            self.last_angle = angle  # Armazena o último ângulo
        elif model == "matrix":
            # Movimento restrito em uma matriz (grid)
            direction = random.choice(["up", "down", "left", "right"])
            if direction == "up":
                dx, dy = 0, self.speed
            elif direction == "down":
                dx, dy = 0, -self.speed
            elif direction == "left":
                dx, dy = -self.speed, 0
            else:  # right
                dx, dy = self.speed, 0

        elif model == "levy_walk":
            step_size = np.random.pareto(1.5) * self.speed  # Movimento baseado em uma distribuição de Pareto
            angle = random.uniform(0, 2 * np.pi)
            dx = step_size * np.cos(angle)
            dy = step_size * np.sin(angle)

        else:
            raise ValueError(f"Modelo de mobilidade desconhecido: {model}")

        new_x = max(0, min(area_size, self.x + dx))
        new_y = max(0, min(area_size, self.y + dy))

        self.x, self.y = new_x, new_y
        return time_interval, (self.x, self.y)


    def get_device_report(self):
        """Retorna informações detalhadas do dispositivo para análise da rede."""
        return {
            "Device ID": self.device_id,
            "SF": self.sf,
            "Freq (MHz)": self.freq,
            "SNR": self.snr,
            "RSSI": self.rssi,
            "Classe LoRaWAN": self.lorawan_class,
            "Energy Consumed (mWh)": self.energy_model.energy_consumed
        }

    def can_receive_downlink(self, current_time):
        """
        Determina se o dispositivo pode receber um downlink baseado na sua classe LoRaWAN.
        - Classe A: Pode receber downlink apenas em janelas periódicas.
        - Classe B: Pode receber downlink a cada 5 segundos.
        - Classe C: Pode receber downlink o tempo todo.
        """
        if self.lorawan_class == 'A':
            return current_time % 10 == 0  # Recebe downlink a cada 10 segundos
        elif self.lorawan_class == 'B':
            return current_time % 5 == 0  # Recebe downlink a cada 5 segundos
        elif self.lorawan_class == 'C':
            return True  # Sempre pode receber downlink

        return False  # Caso padrão (nenhuma classe atribuída corretamente)

    def update_coverage_status(self):
        """Atualiza o status de cobertura do dispositivo verificando se há um Gateway acessível."""
        # Obtém o melhor gateway e o RSSI calculado
        best_gateway, _, best_rssi = self.network.find_best_gateway(self)

        # Calcula a sensibilidade do dispositivo com base no SF e BW
        sensibility = self.set_sensibilidade(self.sf, self.bw)

        # Verifica se o dispositivo está dentro da cobertura
        if best_gateway is None or best_rssi < sensibility:
            self.coverage_status = False
        else:
            self.coverage_status = True

"""##Gateway"""

class Gateway:
    def __init__(self, gw_id, x, y, network, max_capacity=100):
        """
        Inicializa um Gateway LoRaWAN.

        :param gw_id: Identificador do gateway.
        :param x, y: Coordenadas do gateway na rede.
        :param network: Referência à rede principal.
        :param max_capacity: Capacidade máxima de pacotes armazenados no gateway.
        """
        self.gw_id = gw_id
        self.x = x
        self.y = y
        self.network = network  # Referência à rede principal
        self.received_packets = []  # 📡 Pacotes recebidos
        self.max_capacity = max_capacity  # 🏗️ Capacidade máxima do gateway
        self.assigned_frequencies = set()  # 🔄 Frequências alocadas dinamicamente

    def process_uplink(self, packet):
        """
        Processa um pacote uplink recebido de um dispositivo.
        Se o gateway estiver congestionado, tenta redirecionar para outro gateway disponível.
        """
        if not packet or not hasattr(packet, 'device_id'):
            print(f"📦❌ [LOG GATEWAY] Pacote inválido recebido no Gateway {self.gw_id}. Ignorando...")
            return

        device = next((d for d in self.network.devices if d.device_id == packet.device_id), None)
        if not device:
            print(f"📡❌ [LOG GATEWAY] Dispositivo {packet.device_id} não encontrado na rede.")
            return

        distance = max(np.sqrt((device.x - self.x) ** 2 + (device.y - self.y) ** 2 +
                               (self.network.ht_m - self.network.hr_m) ** 2), 0.1)

        path_loss = self.network.pathloss(distance, device.freq, model_pathloss=self.network.model_pathloss)
        packet.rssi = device.tx_power - path_loss

        interference_power = sum(
            10 ** ((other.tx_power - self.network.pathloss(distance, other.freq, model_pathloss=self.network.model_pathloss)) / 10)
            for other in self.network.devices if other.device_id != device.device_id and other.freq == device.freq
        )

        packet.sir = packet.rssi - (10 * np.log10(interference_power) if interference_power > 0 else float('-inf'))

        # Cálculo do noise floor com base no modelo e largura de banda
        packet.noise_floor = self.network.calculate_noise_floor(device.bw)

        packet.snr = packet.rssi - packet.noise_floor
        device.snr = packet.snr

        print(f"📦✔️🗼 [LOG GATEWAY] Pacote do Dispositivo {packet.device_id} recebido pelo Gateway {self.gw_id} | "
              f"RSSI: {packet.rssi:.2f} dBm | SNR: {packet.snr:.2f} dB | SIR: {packet.sir:.2f} dB | Noise Floor: {packet.noise_floor:.2f} dBm")

        if len(self.received_packets) >= self.max_capacity:
            print(f"🗼⚠️ [LOG GATEWAY] Gateway {self.gw_id} sobrecarregado! Tentando balancear carga...")
            self.balance_load(packet)
            return

        self.received_packets.append(packet)  # 📡 Armazena o pacote no gateway

        self.network.lorawan_mac.process_mac_commands(device)



    def balance_load(self, packet):
        """
        Redireciona pacotes para outro gateway menos congestionado.

        :param packet: Pacote a ser balanceado.
        """

        closest_gateway, _, _ = self.network.find_best_gateway(avoid_congestion=True)

        if closest_gateway:
            closest_gateway.received_packets.append(packet)
            print(f"📡🔃🗼 [LOG GATEWAY] Pacote do dispositivo {packet.device_id} encaminhado de Gateway {self.gw_id} ➝ {closest_gateway.gw_id}")
        else:
            print(f"📡❌🗼 [LOG GATEWAY] Nenhum gateway disponível para balanceamento. Pacote será processado localmente.")
            self.received_packets.append(packet)



    def relay_packet(self, packet):
        """
        Simula a retransmissão de um pacote para outro gateway caso necessário.
        """
        alternative_gateway = self.network.find_best_gateway(avoid_congestion=True)

        if alternative_gateway:
            alternative_gateway.received_packets.append(packet)
            print(f"📡🔃 [LOG GATEWAY] Pacote retransmitido do Gateway {self.gw_id} ➝ {alternative_gateway.gw_id}")
        else:
            print(f"📡❌ [LOG GATEWAY] Nenhum gateway disponível para retransmissão. Pacote pode ser perdido.")

    def dynamic_frequency_assignment(self):
        """
        Ajusta dinamicamente as frequências dos gateways para minimizar interferências.
        """
        if not self.network.frequency_mhz:
            print(f"♒❌ [LOG GATEWAY] Nenhuma frequência disponível para alocação no Gateway {self.gw_id}.")
            return

        self.assigned_frequencies.clear()
        available_frequencies = set(self.network.frequency_mhz)
        used_frequencies = {packet.freq for packet in self.received_packets}

        free_frequencies = available_frequencies - used_frequencies
        if free_frequencies:
            new_freq = random.choice(list(free_frequencies))
            self.assigned_frequencies.add(new_freq)
            print(f"♒☑️ [LOG GATEWAY] Gateway {self.gw_id} alocou dinamicamente a frequência {new_freq} MHz.")

    def clear_old_packets(self):
        """
        Remove pacotes antigos da fila de processamento para liberar espaço.
        """
        if len(self.received_packets) > self.max_capacity:
            self.received_packets = self.received_packets[-self.max_capacity:]
            print(f"🧹 [LOG GATEWAY] Gateway {self.gw_id}: Pacotes mais antigos foram removidos para liberar espaço.")

"""##Protocolos"""

class LoRaWANMAC:
    def __init__(self, network=None):
        """
        Inicializa o gerenciamento MAC para a rede LoRaWAN.

        Parâmetros:
        - network: Referência à rede para acessar dispositivos e configurações.
        """
        self.device_sessions = {}  # Sessões ativas (OTAA)
        self.downlink_queue = {}  # Buffer de pacotes downlink
        self.network = network  # Referência à rede principal

    def join_request(self, device):
        """
        Simula uma solicitação OTAA (Over-the-Air Activation) para ingressar na rede.
        """
        if device.device_id not in self.device_sessions:
            self.device_sessions[device.device_id] = {
                "dev_addr": f"00FF{device.device_id:04X}",  # Endereço fictício do dispositivo
                "session_key": f"SK-{device.device_id:04X}",  # Chave de sessão fictícia
                "joined": True
            }
            print(f"☑️ [LOG LORAMAC] Dispositivo {device.device_id} entrou na rede LoRaWAN.")

    def process_mac_commands(self, device):
        """
        Aplica o ADR (Adaptive Data Rate), ajustando SF e potência de transmissão com base no RSSI e SNR.
        """
        if device.device_id not in self.device_sessions:
            return  # 🚫 Dispositivo não registrado na rede

        if not device.adr_enabled:
            print(f"⚠️🛑 [LOG LORAMAC] ADR desativado para Dispositivo {device.device_id}. Nenhum ajuste será feito.")
            return

        # Limiares definidos para ajustar o SF e Tx Power
        SNR_HIGH_THRESHOLD = 8     # Reduz SF se SNR for maior que isso
        SNR_LOW_THRESHOLD = -20    # Aumenta SF se SNR for menor que isso
        RSSI_HIGH_THRESHOLD = -90  # Reduz potência se RSSI for maior que isso
        RSSI_LOW_THRESHOLD = -130  # Aumenta potência se RSSI for menor que isso
        HIST_SIZE = 10             # Tamanho do histórico para suavização

        # Calcula a sensibilidade do dispositivo com base no SF e na largura de banda (BW)
        sensibility = device.set_sensibilidade(device.sf, device.bw)

        # Atualiza os históricos de SNR e RSSI
        if device.snr is not None:
            device.snr_history.append(device.snr)
            if len(device.snr_history) > HIST_SIZE:
                device.snr_history.pop(0)

        if device.rssi is not None:
            device.rssi_history.append(device.rssi)
            if len(device.rssi_history) > HIST_SIZE:
                device.rssi_history.pop(0)

        # Se o histórico não tem o tamanho necessário, aguarda mais amostras
        if len(device.snr_history) < HIST_SIZE or len(device.rssi_history) < HIST_SIZE:
            return  # Aguarda dados suficientes antes de aplicar mudanças

        # Calcula as médias de SNR e RSSI
        avg_snr = max(device.snr_history)
        avg_rssi = np.mean(device.rssi_history)

        # Exibe as médias de SNR e RSSI para controle
        print(f"🚩 [LOG LORAMAC] ADR | Device {device.device_id} | Avg SNR: {avg_snr:.2f} dB | Avg RSSI: {avg_rssi:.2f} dBm | "
              f"SF: {device.sf} | Tx Power: {device.tx_power} dBm | Sensibilidade: {sensibility} dBm")

        # Exibe o SF e Tx Power antes da mudança
        #print(f"🔙 [LOG LORAMAC] Antes do ADR | Device {device.device_id} | SF: {device.sf} | Tx Power: {device.tx_power} dBm")

        # Calcula a nova potência de transmissão (Tx Power)
        new_tx_power = device.tx_power
        if avg_rssi > RSSI_HIGH_THRESHOLD:
            new_tx_power = max(2, device.tx_power - 1)  # Reduz potência lentamente
        elif avg_rssi < RSSI_LOW_THRESHOLD:
            new_tx_power = min(25, device.tx_power + 1)  # Aumenta potência gradualmente

        # Calcula o novo SF
        new_sf = device.sf
        if avg_snr > SNR_HIGH_THRESHOLD and new_tx_power <= 10:
            new_sf = max(7, device.sf - 1)  # Reduz SF se possível
        elif avg_snr < SNR_LOW_THRESHOLD and new_tx_power >= 10:
            new_sf = min(12, device.sf + 1)  # Aumenta SF para melhorar alcance

        # Se houve alteração no SF ou Tx Power, aplica a mudança no dispositivo
        if new_tx_power != device.tx_power or new_sf != device.sf:
            print(f"↪️ [LOG LORAMAC] ADR Ajustado | Device {device.device_id} -> SF: {new_sf}, Tx Power: {new_tx_power} dBm")
            device.tx_power = new_tx_power  # Atualiza Tx Power
            device.sf = new_sf  # Atualiza SF

        # Exibe o SF e Tx Power após a mudança
        #print(f"🔜 [LOG LORAMAC] Depois do ADR | Device {device.device_id} | SF: {device.sf} | Tx Power: {device.tx_power} dBm")

        def handle_ack(self, packet):
            """
            Processa pacotes com flag de ACK, verificando se devem ser retransmitidos.
            """
            if packet.received:
                print(f"🔰 [LOG LORAMAC] ACK recebido para o pacote do Dispositivo {packet.device_id}")
                return True
            else:
                print(f"🔰❌ [LOG LORAMAC] Nenhum ACK para Dispositivo {packet.device_id}, retransmitindo...")
                return False

        def manage_downlink(self, device):
            """
            Gerencia o envio de pacotes downlink para um dispositivo.
            """
            if device.device_id in self.downlink_queue:
                downlink_packet = self.downlink_queue.pop(device.device_id)
                print(f"🗼🔃📡 [LOG LORAMAC] Pacote enviado para Dispositivo {device.device_id} via Gateway.")
                self.network.packet_tracker.add_packet(downlink_packet)
                return downlink_packet
            return None

    def send_mac_commands(self):
        """
        Aplica ADR para otimizar a comunicação dos dispositivos na rede.
        - Ajusta SF e potência de transmissão de acordo com o SNR e RSSI médio.
        """
        if not self.network.adr_enabled:
            print("🛑❌ [LOG LORAMAC] ADR desativado globalmente. Nenhum ajuste será feito.")
            return

        for device in self.network.devices:
            if not device.adr_enabled:
                continue  # Pula dispositivos com ADR desativado individualmente

            self.process_mac_commands(device)

    def check_ack(self, device_id, time):
        """
        Simula a verificação de um ACK para um dispositivo.
        """
        return random.random() > 0.5  # Simulação simples (50% de chance de receber um ACK)

"""##Throughput"""

class NetworkThroughput:
    def __init__(self, network):
        """
        Inicializa o cálculo da vazão da rede.

        Parâmetros:
        - network: Referência ao objeto da classe Network para acessar dispositivos e parâmetros da rede.
        """
        self.network = network

    def calculate_sf_proportions(self):
        """
        Calcula a proporção de dispositivos que utilizam cada Spreading Factor (SF).

        Retorna:
        - Um dicionário {SF: proporção} indicando a porcentagem de dispositivos usando cada SF.
        """
        total_devices = len(self.network.devices)
        sf_counts = {sf: 0 for sf in range(7, 13)}

        for device in self.network.devices:
            sf_counts[device.sf] += 1

        # 🔹 Evita divisão por zero
        sf_proportions = {sf: (sf_counts[sf] / total_devices) if total_devices > 0 else 0 for sf in sf_counts}

        print(f"📊 [LOG NETWORKTHROUGHPUT] Proporção de dispositivos para SF: {sf_proportions}")
        return sf_proportions

    def calculate_avg_airtime(self):
        """
        Calcula o tempo médio de transmissão no ar (ToA) para cada SF.

        Retorna:
        - Um dicionário {SF: ToA médio} indicando a média de airtime por SF.
        """
        avg_airtime = {}
        for sf in range(7, 13):  # SF7 a SF12
            devices_with_sf = [device.calculate_airtime() for device in self.network.devices if device.sf == sf]
            avg_airtime[sf] = np.mean(devices_with_sf) if devices_with_sf else 0

        print(f"📊 [LOG NETWORKTHROUGHPUT] Tempo médio de transmissão (ToA) por SF: {avg_airtime}")
        return avg_airtime

    def calculate_covered_devices(self):
        """
        Conta o número total de dispositivos dentro da cobertura.

        Retorna:
        - Número total de dispositivos cobertos.
        """
        covered_devices = sum(1 for device in self.network.devices if device.coverage_status)

        return covered_devices

    def calculate_traffic_load(self):
        """
        Calcula a carga de tráfego G para cada SF.

        Retorna:
        - Um dicionário {SF: G} com a carga de tráfego por Spreading Factor.
        """
        G = {}
        sf_proportions = self.calculate_sf_proportions()
        avg_airtime = self.calculate_avg_airtime()

        for sf in range(7, 13):  # SF7 a SF12
            Nc = sum(1 for device in self.network.devices if device.sf == sf)  # Número de nós com este SF
            Ps = sf_proportions[sf]  # Proporção de nós com este SF
            toa = avg_airtime[sf]  # Tempo médio de transmissão
            G[sf] = 46 * Nc * Ps * toa  # Carga de tráfego para este SF

        print(f"📊 [LOG NETWORKTHROUGHPUT] Carga de tráfego G por SF: {G}")
        return G

    def calculate_total_throughput(self):
        """
        Calcula a vazão total T da rede.

        Retorna:
        - Vazão total da rede em bits por segundo.
        """
        sf_proportions = self.calculate_sf_proportions()  # Ps[sf]
        avg_airtime = self.calculate_avg_airtime()  # ToA médio por SF
        G = self.calculate_traffic_load()  # Carga de tráfego para cada SF
        Nc = self.calculate_covered_devices()  # Número total de nós cobertos


        if Nc == 0:
            print("⚠️ [LOG NETWORKTHROUGHPUT] Nenhum dispositivo dentro da cobertura. Vazão total = 0.")
            return 0


        T = sum(
            46 * sf_proportions[sf] * Nc * np.exp(-2 * G[sf] / 10000)
            for sf in G if G[sf] > 0
        )

        print(f"📡 [LOG NETWORKTHROUGHPUT] Vazão total da rede: {T:.2f} bits/s")
        return T

"""##Network"""

class Network:
    def __init__(self, num_devices, num_gateways, area_size, lambda_rate, speed, sf_range, tx_power, frequency_mhz, ht_m, hr_m, bw, cr, pl, simulation_time, adr_enabled, pathloss):

        self.frequency_mhz = frequency_mhz  # Frequências disponíveis (MHz)
        self.ht_m = ht_m  # Altura dos dispositivos (m)
        self.hr_m = hr_m  # Altura dos gateways (m)
        self.bw = bw  # Largura de banda (Hz)
        self.cr = cr  # Taxa de codificação
        self.pl = pl  # Payload dos pacotes
        self.simulation_time = simulation_time  # Tempo total da simulação
        self.adr_enabled = adr_enabled  # Controle do Adaptive Data Rate (ADR)
        self.num_devices = num_devices  # Número total de dispositivos
        self.num_gateways = num_gateways  # Número total de gateways
        self.area_size = area_size  # Área da rede (km²)
        self.lambda_rate = lambda_rate  # Taxa de movimento dos dispositivos
        self.speed = speed  # Velocidade dos dispositivos
        self.sf_range = sf_range  # Spreading Factors disponíveis
        self.tx_power = tx_power  # Potência de transmissão
        self.device_data = []
        self.devices = []  # Lista para armazenar dispositivos
        self.gateways = []  # Lista para armazenar gateways
        self.positions = {"devices": {}, "gateways": {}}  # Dicionário de posições
        self.packet_tracker = PacketTracker()  # Rastreamento de pacotes
        self.lorawan_mac = LoRaWANMAC(self)  # Gerenciamento MAC do LoRaWAN
        self.network_throughput = NetworkThroughput(self)
        self.throughput_calculator = NetworkThroughput(self)
        self.current_time = 0
        self.initialize_devices()
        self.mobility_enabled = mobility_enabled
        self.model_pathloss = model_pathloss

        self.initialize_gateways()
        for device in self.devices:
            device.update_coverage_status()

    def calculate_noise_floor(self, bw):
        """
        Calcula o valor do ruído de fundo (noise floor) em dBm com base na largura de banda (BW) do dispositivo.
        :param bw: Largura de banda (em Hz)
        :return: O valor do noise floor em dBm.
        """
        noise_floor = 10 * np.log10(k * temperatura * bw) - noise_figure
        return noise_floor

    def initialize_devices(self):
        """Inicializa os dispositivos finais em grade (matrix)."""
        rows = int(np.ceil(np.sqrt(self.num_devices)))
        cols = int(np.ceil(self.num_devices / rows))
        x_grid = np.linspace(0, self.area_size, cols, endpoint=False) + (self.area_size / (2 * cols))
        y_grid = np.linspace(0, self.area_size, rows, endpoint=False) + (self.area_size / (2 * rows))

        for i in range(self.num_devices):
            r = i // cols
            c = i % cols
            x, y = x_grid[c], y_grid[r]
            device = EndDevice(
                device_id=i,
                x=x, y=y,
                lambda_rate=self.lambda_rate,
                speed=self.speed,
                sf_range=self.sf_range,
                tx_power=self.tx_power,
                bw=self.bw,
                cr=self.cr,
                pl=self.pl,
                frequency_mhz=self.frequency_mhz,
                network=self
            )
            device.adr_enabled = self.adr_enabled
            self.devices.append(device)
            self.positions["devices"][i] = (x, y)


    def initialize_gateways(self):
        """Inicializa os gateways em grade (matrix)."""
        rows = int(np.ceil(np.sqrt(self.num_gateways)))
        cols = int(np.ceil(self.num_gateways / rows))
        x_grid = np.linspace(0, self.area_size, cols, endpoint=False) + (self.area_size / (2 * cols))
        y_grid = np.linspace(0, self.area_size, rows, endpoint=False) + (self.area_size / (2 * rows))

        for i in range(self.num_gateways):
            r = i // cols
            c = i % cols
            x, y = x_grid[c], y_grid[r]
            gateway = Gateway(
                gw_id=i,
                x=x, y=y,
                network=self
            )
            self.gateways.append(gateway)
            self.positions["gateways"][i] = (x, y)


    def toggle_adr(self):
        """Ativa/desativa ADR para toda a rede."""

        self.adr_enabled = adr_enabled

        for device in self.devices:
            device.adr_enabled = self.adr_enabled
        print(f"🛑 [LOG NETWORK] ADR {'ATIVADO' if self.adr_enabled else 'DESATIVADO'} para toda a rede.")

    def set_mobility(self, mobility_enabled):
        """Ativa ou desativa a mobilidade dos dispositivos e exibe um log."""
        for device in self.devices:
            device.mobility_enabled = mobility_enabled


        status = "ativada" if mobility_enabled else "desativada"
        print(f"🚀 [LOG] Mobilidade {status}. Dispositivos {'irão se mover' if mobility_enabled else 'permanecerão fixos'}.")


    def get_propagation_delay(self, distance):
        """Retorna o atraso de propagação baseado na distância (s)."""
        return distance / 3e8

    def export_device_log(self, device_data, filename="device_log.csv"):
        """
        Exporta os dados detalhados dos dispositivos para um arquivo CSV.
        Inclui informações como posição, RSSI, SNR, SF, etc.

        :param device_data: Dados dos dispositivos a serem exportados.
        :param filename: Nome do arquivo CSV de saída (padrão: "device_log.csv").
        """

        try:

            with open(filename, mode="w", newline="") as file:
                writer = csv.writer(file)

                writer.writerow(["Tempo", "Device ID", "SF", "RSSI", "SNR", "Posição (X, Y)", "Distância do Gateway"])

                for data in device_data:
                    writer.writerow([data["time"], data["device_id"], data["sf"], data["rssi"], data["snr"], data["position"], data["distance"]])

            print(f"📄 Log dos dispositivos exportado para {filename}")

        except Exception as e:
            print(f"❌ Erro ao exportar log dos dispositivos: {e}")


    def simulate_transmissions(self):
        """Simula a transmissão de pacotes na rede, aplicando mobilidade, ADR e retransmissões."""
        print("📡 [LOG NETWORK] Iniciando Simulação de Transmissões...")
        self.current_time = 0
        total_transmissions, total_retransmissions = 0, 0
        self.energy_log = []  # Para armazenar os dados de consumo de energia

        # Inicializa a lista de dados dos dispositivos para exportação
        device_data = []

        while self.current_time < self.simulation_time:
            print(f"⏳ [LOG NETWORK] Tempo da Simulação: {self.current_time}")

            for device in self.devices:
                print(f"🔍 [LOG NETWORK] Avaliando Dispositivo {device.device_id}")

                # Movimenta o dispositivo se a mobilidade estiver habilitada
                if device.mobility_enabled:
                    _, new_position = device.move(self.area_size, device.mobility_enabled, device.model)
                    self.positions["devices"][device.device_id] = new_position  # Apenas mantém a última posição

                    # Atualiza o status de cobertura do dispositivo
                    device.update_coverage_status()
                    print(f"📍 [LOG NETWORK] Dispositivo {device.device_id} movido para {new_position} | Cobertura: {device.coverage_status}")

                # Obtém o melhor gateway, distância e RSSI
                best_gateway, best_distance, best_rssi = self.find_best_gateway(device)

                # Sensibilidade do dispositivo
                sensibility = device.set_sensibilidade(device.sf, device.bw)

                # Verifica se o dispositivo está dentro da cobertura e se o RSSI é adequado
                if best_gateway is None or not device.coverage_status or (best_rssi is not None and best_rssi < sensibility):
                    print(f"⚠️⬇️[LOG NETWORK] Dispositivo {device.device_id} ignorado (fora da cobertura ou RSSI insuficiente).")
                    continue

                # Coleta os dados do dispositivo
                device_data.append({
                    "time": self.current_time,
                    "device_id": device.device_id,
                    "sf": device.sf,
                    "tx_power": device.tx_power,
                    "rssi": best_rssi,
                    "snr": device.snr,
                    "position": (device.x, device.y),
                    "distance": best_distance,
                    "sensibilidade": sensibility,
                    "largura de banda": device.bw,
                    "potência de transmissão": device.tx_power,
                    "frequência": device.freq,
                })

                # Transmissão do pacote
                packet = device.transmit(self.current_time)
                if packet:
                    print(f"📦✅ [LOG NETWORK] Pacote Criado pelo Dispositivo {device.device_id}")

                    # Processamento do pacote no gateway
                    best_gateway.process_uplink(packet)
                    self.packet_tracker.add_packet(packet)
                    total_transmissions += 1

                    print(f"📍 [LOG NETWORK] Pacote enviado pelo Dispositivo {device.device_id} | SF:{packet.sf} TP: {device.tx_power} → Gateway {best_gateway.gw_id} "
                          f"| RSSI: {packet.rssi:.2f} dBm | SNR: {packet.snr:.2f} dB | SIR: {packet.sir:.2f} dB ")

                    # Se ADR estiver ativado, aplica as mudanças
                    if self.adr_enabled:
                        print(f"🛑🛑[LOG NETWORK] Aplicando ADR no Dispositivo {device.device_id}")
                        self.lorawan_mac.process_mac_commands(device)

                    # Detecta colisões e interferências
                    self.detect_collisions_and_interference()

                    # Se houve colisão, tenta retransmitir
                    if packet.collided:
                        print(f"💥💥♻️ [LOG NETWORK] Pacote do dispositivo {packet.device_id} colidiu! Iniciando retransmissão...")
                        retransmissions = self.handle_retransmission(device, packet)
                        total_retransmissions += retransmissions

            # Incrementa o tempo de simulação
            self.current_time += 1

            # Calcula e armazena o consumo total de energia da rede a cada segundo
            total_energy = sum(device.energy_model.energy_consumed for device in self.devices) /1000
            #print(f"***********[LOG NETWORK] total de energia{total_energy/1000}")
            self.energy_log.append(total_energy)

        # Ao final da simulação, exporta os dados dos dispositivos
        self.export_device_log(device_data)

        # Imprime as estatísticas finais
        self.print_statistics(total_transmissions, total_retransmissions)
        print("✅ [LOG NETWORK] Simulação de Transmissões Concluída.")




    def detect_collisions_and_interference(self):
        """Detecta colisões entre pacotes transmitidos na mesma SF, frequência e com o mesmo RSSI."""

        self.packet_tracker.packets.sort(key=lambda p: p.arrival_time)

        for i, p1 in enumerate(self.packet_tracker.packets):
            for p2 in self.packet_tracker.packets[i + 1:]:
                if p2.arrival_time >= p1.arrival_time + p1.rectime:
                    break


                if p1.device_id == p2.device_id:
                    continue

                if p1.sf == p2.sf and p1.freq == p2.freq and abs(p1.rssi - p2.rssi) < 0.1:
                    p1.collided = p2.collided = True
                    #print(f"⚠️ [LOG NETWORK] Pacotes de Dispositivos {p1.device_id} e {p2.device_id} colidiram! (SF={p1.sf}, Freq={p1.freq}, RSSI={p1.rssi:.2f} dBm)")



    def handle_retransmission(self, device, packet):
        """Gerencia retransmissões em caso de colisão e conta quantas vezes um pacote é retransmitido."""
        retransmissions = 0  # ✅ Inicializa contador de retransmissões

        while packet.collided and retransmissions < device.max_retransmissions:
            print(f"🔄 [LOG NETWORK] Tentativa de retransmissão {retransmissions + 1} para o Dispositivo {device.device_id}")

            if device.wait_for_ack(self.current_time):
                print(f"✅ [LOG NETWORK] Pacote {packet.device_id} confirmado via ACK. Nenhuma retransmissão necessária.")
                return retransmissions


            backoff_time = random.uniform(1, 10) * (2 ** retransmissions)
            retransmission_time = self.current_time + backoff_time

            print(f"🔄 [LOG NETWORK] Dispositivo {device.device_id} aguardando {backoff_time:.2f}s antes da retransmissão (Tentativa {retransmissions + 1})")

            retransmitted_packet = device.transmit(retransmission_time)

            if retransmitted_packet:

                self.packet_tracker.add_packet(retransmitted_packet, is_retransmission=True)
                self.packet_tracker.total_retransmissions += 1  # ✅ Atualiza contador global
                retransmissions += 1  # ✅ Incrementa contador local

                print(f"🔄 [LOG NETWORK] Retransmissão realizada: Dispositivo {device.device_id} | Tentativa {retransmissions} | Tempo: {retransmission_time:.2f}s")

            if retransmissions >= device.max_retransmissions:
                print(f"❌ [LOG NETWORK] Dispositivo {device.device_id} atingiu o limite de {device.max_retransmissions} retransmissões. Pacote descartado.")

        return retransmissions  # ✅ Retorna total de retransmissões realizadas



    def find_best_gateway(self, device=None, avoid_congestion=False):
        """
        Encontra o melhor gateway disponível para um dispositivo, considerando:
        - Melhor RSSI se avoid_congestion=False (para conexão inicial).
        - Gateway menos congestionado se avoid_congestion=True (para balanceamento de carga).
        """
        available_gateways = []

        for gateway in self.gateways:
            if device:
                # Calcular a distância entre o dispositivo e o gateway
                distance = max(np.sqrt((device.x - gateway.x) ** 2 + (device.y - gateway.y) ** 2 +
                                      (self.ht_m - self.hr_m) ** 2), 0.1)

                # Calcular o path loss com base na distância e frequência
                path_loss = self.pathloss(distance, device.freq, model_pathloss=self.model_pathloss)

                # Sensibilidade do dispositivo com base no SF e BW
                rssi = device.tx_power - path_loss

                # Chama o método set_sensibilidade do dispositivo (EndDevice)
                sensibility = device.set_sensibilidade(device.sf, device.bw)  # A função deve ser acessada aqui
                #print(f"LOG NETWORK Device : {device.device_id} | Sensibilidade:  {sensibility} |  BW: {device.bw} | SF : {device.sf} | RSSI: {rssi}")

                # Comparar RSSI com a sensibilidade do dispositivo
                if rssi > sensibility:
                    available_gateways.append((gateway, distance, rssi))

            else:
                available_gateways.append((gateway, None, None))

        if not available_gateways:
            return None, None, None

        if avoid_congestion:
            # Se evitar congestionamento, escolhe o gateway com menor carga
            return min(available_gateways, key=lambda x: len(x[0].received_packets))

        if device:
            # Se não evitar congestionamento, escolhe o gateway com melhor RSSI
            return max(available_gateways, key=lambda x: x[2])

        return None, None, None






    def pathloss(self, distance, frequency_mhz, model_pathloss, fading_type=None):
        """Calcula a perda de percurso usando diferentes modelos de propagação.

        Parâmetros:
        - distance: Distância entre transmissor e receptor (km).
        - frequency_mhz: Frequência de operação (MHz).
        - model_pathloss: Modelo de propagação a ser usado:
            * "okumura_hata"
            * "log_distance"
            * "fspl" (Free-Space Path Loss)
            * "cost_hata"
            * "fading" (Path Loss + Fading Avançado)
        - fading_type: Tipo de fading a ser aplicado (se "fading" for escolhido)
            * "rayleigh"
            * "rician"
            * "nakagami"

        Retorna:
        - path_loss: Perda de percurso em dB.
        """

        if distance <= 0:
            return float('inf')  # Evita erro se a distância for zero ou negativa

        if model_pathloss == "okumura_hata":

            correction_factor = (1.1 * np.log10(frequency_mhz) - 0.7) * self.hr_m - (1.56 * np.log10(frequency_mhz) - 0.8)
            path_loss = (
                69.55 + 26.16 * np.log10(frequency_mhz)
                - 13.82 * np.log10(self.ht_m)
                - correction_factor
                + (44.9 - 6.55 * np.log10(self.ht_m)) * np.log10(distance)
            )

        elif model_pathloss == "log_distance":

            path_loss_exponent = 3.5  # Coeficiente de perda para ambientes urbanos
            path_loss = 20 * np.log10(frequency_mhz) + 10 * path_loss_exponent * np.log10(distance) - 28

        elif model_pathloss == "fspl":

            path_loss = 20 * np.log10(distance) + 20 * np.log10(frequency_mhz) + 32.45

        elif model_pathloss == "cost_hata":

            correction_factor = (1.1 * np.log10(frequency_mhz) - 0.7) * self.hr_m - (1.56 * np.log10(frequency_mhz) - 0.8)
            path_loss = (
                46.3 + 33.9 * np.log10(frequency_mhz)
                - 13.82 * np.log10(self.ht_m)
                - correction_factor
                + (44.9 - 6.55 * np.log10(self.ht_m)) * np.log10(distance)
            )

        elif model_pathloss == "fading":

            base_loss = self.pathloss(distance, frequency_mhz, model_pathloss)

            if fading_type == "rayleigh":
                fading_factor = np.random.rayleigh(scale=2)  # Desvanecimento Rayleigh
            elif fading_type == "rician":
                fading_factor = np.random.rician(3, 1)  # Desvanecimento Rician (LOS)
            elif fading_type == "nakagami":
                fading_factor = np.random.gamma(shape=3, scale=2)  # Nakagami-m
            else:
                fading_factor = 0  # Sem fading

            path_loss = base_loss + fading_factor  # Aplica o efeito do fading

# """
#============================================================================================================
#""   Modelo de propagação  (rede neural)
#============================================================================================================
# """
        else:
            raise ValueError(f"Modelo de propagação desconhecido: {model}")

        return path_loss



        rural_correction = 4.78 * (np.log10(frequency_mhz) ** 2) - 18.33 * np.log10(frequency_mhz) + 40.94
        return path_loss_urban - rural_correction  # Retorna a perda de percurso final

    def print_statistics(self, total_transmissions=0, total_retransmissions=0):
        """Exibe estatísticas finais da simulação com formatação aprimorada."""
        stats = self.packet_tracker.get_stats()

        total_transmissions = stats.get("Total Pacotes", total_transmissions)
        total_retransmissions = stats.get("Retransmissões", total_retransmissions)
        total_colisoes = stats.get("Colisões", 0)
        pacotes_sucesso = stats.get("Entregues com Sucesso", 0)
        pdr = stats.get("Taxa de Entrega (PDR)", 0.0)

        retransmission_rate = (total_retransmissions / total_transmissions * 100) if total_transmissions > 0 else 0
        covered_devices = self.throughput_calculator.calculate_covered_devices()
        network_throughput = self.throughput_calculator.calculate_total_throughput()  # ✅ Adicionando a vazão total da rede

        print("\n" + "=" * 50)
        print(f"{'📡 Dispositivos Cobertos:':<30} {covered_devices}")
        print(f"{'📦 Total de Pacotes:':<30} {total_transmissions}")
        print(f"{'♻️ Retransmissões:':<30} {total_retransmissions} ({retransmission_rate:.2f}%)")
        print(f"{'⚠️ Colisões:':<30} {total_colisoes}")
        print(f"{'✅ Pacotes Entregues:':<30} {pacotes_sucesso}")
        print(f"{'📊 PDR (Packet Delivery Ratio):':<30} {pdr:.2f}%")
        print(f"{'📡📊 Vazão Total de Dados:':<30} {network_throughput:.2f} kbps")  # ✅ Mostrando vazão total
        print("=" * 50)



    def plot_statistics(self):
        """Gera gráficos sobre desempenho da rede, incluindo:
        - Distribuição dos Spreading Factors (SF)
        - Energia total consumida ao longo do tempo
        - Distribuição do SNR
        """
        from collections import Counter

        sf_counts = Counter(device.sf for device in self.devices)
        snr_values = [
            np.mean(device.snr) if isinstance(device.snr, (list, np.ndarray)) and device.snr is not None else device.snr
            for device in self.devices if isinstance(device.snr, (int, float))
        ]


        fig, axes = plt.subplots(1, 3, figsize=(15, 5))


        axes[0].bar(sf_counts.keys(), sf_counts.values(), color='blue')
        axes[0].set_xlabel("Spreading Factor")
        axes[0].set_ylabel("Número de Dispositivos")
        axes[0].set_title("Distribuição de SFs")


        if self.energy_log:
            time_steps = range(len(self.energy_log))
            axes[1].plot(time_steps, self.energy_log, marker='o', linestyle='-', color='red')
            axes[1].set_xlabel("Tempo (s)")
            axes[1].set_ylabel("Energia Total Consumida (Wh)")
            axes[1].set_title("Energia Total Consumida ao Longo do Tempo")
        else:
            axes[1].set_title("Sem Dados de Energia")

        if snr_values:
            axes[2].hist(snr_values, bins=10, color='orange', edgecolor='black')
            axes[2].set_xlabel("SNR (dB)")
            axes[2].set_ylabel("Número de Dispositivos")
            axes[2].set_title("Distribuição de SNR")
        else:
            axes[2].set_title("Sem Dados de SNR")

        plt.tight_layout()
        plt.show()

    def plot_mobility(self):
        """Plota a última posição dos dispositivos na rede, diferenciando por SF e cobertura."""

        plt.figure(figsize=(8, 8))


        sf_colors = {7: 'blue', 8: 'green', 9: 'orange', 10: 'purple', 11: 'brown', 12: 'pink'}
        plotted_labels = set()

        fora_cobertura_legenda = False

        for device in self.devices:
            pos_list = self.positions["devices"].get(device.device_id, [])

            if isinstance(pos_list, tuple):
                pos_list = [pos_list]  # Converte para lista com um único item

            if not pos_list or not isinstance(pos_list[-1], (tuple, list)):
                print(f"⚠️ [LOG] Posição inválida para Dispositivo {device.device_id}: {pos_list}")
                continue  # Evita erro se `pos_list` for vazio ou inválido

            last_position = pos_list[-1]  # Obtém a última posição registrada
            x_val, y_val = last_position  # Desempacota (x, y)

            if not device.coverage_status:
                color = 'gray'
                label = "Fora da Cobertura"

                if not fora_cobertura_legenda:
                    plt.scatter(x_val, y_val, marker='o', color=color, label=label)
                    fora_cobertura_legenda = True
                else:
                    plt.scatter(x_val, y_val, marker='o', color=color)

            else:
                color = sf_colors.get(device.sf, 'black')
                label = f'SF {device.sf}'

                if label not in plotted_labels:
                    plt.scatter(x_val, y_val, marker='o', color=color, label=label)
                    plotted_labels.add(label)
                else:
                    plt.scatter(x_val, y_val, marker='o', color=color)

        for gw_id, (x, y) in self.positions["gateways"].items():
            label = f'Gateway {gw_id}'
            if label not in plotted_labels:
                plt.scatter(x, y, marker='s', color='red', label=label, s = 100)
                plotted_labels.add(label)
            else:
                plt.scatter(x, y, marker='s', color='red')

        plt.xlim(0, self.area_size)
        plt.ylim(0, self.area_size)

        plt.xlabel("X Position")
        plt.ylabel("Y Position")
        plt.title("Última Posição dos End Devices diferenciados por SF e cobertura")
        plt.legend()
        plt.grid()
        plt.show()


    def run_simulation(self):
        print(f"🌐 [DEBUG] Iniciando simulação com {len(self.devices)} dispositivos...")

#==================================================================== Relatório Final ==================================================================

network = Network(num_devices, num_gateways, area_size, lambda_rate, speed, sf_range,
                  tx_power, frequency_mhz, ht_m, hr_m,
                  bw, cr, pl, simulation_time, adr_enabled, model_pathloss)

print(f"\n📡 [DEBUG] Dispositivos ativos na simulação: {len(network.devices)}\n")

network.toggle_adr()
network.set_mobility(mobility_enabled)
network.simulate_transmissions()
network.detect_collisions_and_interference()
stats = network.packet_tracker.get_stats()
covered_devices = network.throughput_calculator.calculate_covered_devices()
network.plot_statistics()
network.plot_mobility()
total_energy = sum(device.energy_model.energy_consumed for device in network.devices)
print(f"⚡ Consumo total de energia da rede: {total_energy:.2f} mWh\n")
